### ISSUE TITLE
WiFi adapter - kext and application

### ISSUE THREAD

**Issue by Windemiatrix** [snajdovski/HP-250-G6-Mojave-EFI#6]
Good day. First - thanks for clover configuration!

I found kext and application, that make WiFi working:
https://github.com/OpenIntelWireless/HeliPort
https://github.com/OpenIntelWireless/itlwm

You could add this information to README.md. I think it will be helpful for others.

**Comment by snajdovski** [comment]
Sure I will add these links, the only problem is the intel driver works on Catalina and later, this repo also supports Mojave (its focused to work more on it), but sure thank you for the suggestion.
